apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: registry.cn-beijing.aliyuncs.com/qingfeng666/stress
    resources:
      limits:
        memory: "128Mi"
        cpu: "1"
    ports:
      - containerPort: 80
    args:
      - -cups
      - "2"
