apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - "sh"
      - "-c"
    args:
      - printf UNCHANGED_REFERENCE=$UNCHANGED_REFERENCE'\n'; printf SERVICE=$SERVICE'\n'; printf ESCAPED_SERVICE=$ESCAPED_SERVICE; sleep 120
    env:
      - name: SERVICE_IP
        value: "192.168.99.102"
      - name: SERVICE_PORT
        value: "31111"
      - name: UNCHANGED_REFERENCE
        value: $(PROTOCAL)://$(SERVICE_IP):$(SERVICE_PORT)
      - name: PROTOCAL
        value: "https"
      - name: SERVICE
        value: $(PROTOCAL)://$(SERVICE_IP):$(SERVICE_PORT)
      - name: ESCAPED_SERVICE
        value: $$(PROTOCAL)://$(SERVICE_IP):$(SERVICE_PORT)


    
