apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: busybox:1.28
      command: ['sh','-c','date && sleep 3600']
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  initContainers:
    - name: init-container
      image: busybox:1.28
      command: ['sh','-c','date && sleep 10']