apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: busybox
      command: ["/bin/sh","-c","env|grep app"]
      envFrom:
        - configMapRef:
            name: appvar
  restartPolicy: Never