apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
spec:
  rules:
  - host: client.ubuntu.local
    http:
      paths:
      - path: /
        backend:
         serviceName: grafana
         servicePort: 3000
